// Mock data for Indian Government Schemes
export interface Scheme {
  id: string;
  name: string;
  nameHi: string;
  description: string;
  ministry: string;
  category: string;
  schemeType: 'central' | 'state' | 'private';
  schemeSource?: 'government' | 'private_industry' | 'ngo';
  sourceOrg?: string;
  targetState: string | null;
  benefits: string;
  minAge: number | null;
  maxAge: number | null;
  minIncome: number | null;
  maxIncome: number | null;
  targetGender: 'all' | 'male' | 'female';
  targetCategories: string[];
  targetEducation: string[];
  requiresBpl: boolean;
  requiresFarmer: boolean;
  requiresStudent: boolean;
  requiresDisability: boolean;
  applicationUrl: string;
  deadline: string | null;
  documentsRequired: string[];
  isActive: boolean;
  eligibilityScore?: number;
}

export interface UserProfile {
  id: string;
  phone: string;
  name: string;
  email: string;
  dateOfBirth: string;
  gender: 'male' | 'female' | 'other';
  category: 'general' | 'obc' | 'sc' | 'st' | 'ews';
  state: string;
  district: string;
  annualIncome: number;
  occupation: string;
  educationLevel: 'none' | 'primary' | 'secondary' | 'graduate' | 'postgraduate';
  isDisabled: boolean;
  isMinority: boolean;
  isBpl: boolean;
  isFarmer: boolean;
  isStudent: boolean;
  preferredLanguage: string;
}

export const indianStates = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Puducherry',
  'Chandigarh', 'Andaman & Nicobar Islands', 'Dadra & Nagar Haveli',
  'Lakshadweep'
];

export const schemeCategories = [
  { id: 'agriculture', label: 'Agriculture', icon: '🌾', color: '#22c55e' },
  { id: 'education', label: 'Education', icon: '📚', color: '#3b82f6' },
  { id: 'scholarship', label: 'Scholarships', icon: '🎓', color: '#a855f7' },
  { id: 'health', label: 'Health & Wellness', icon: '🏥', color: '#ef4444' },
  { id: 'housing', label: 'Housing', icon: '🏠', color: '#f59e0b' },
  { id: 'employment', label: 'Employment & Skills', icon: '💼', color: '#8b5cf6' },
  { id: 'women', label: 'Women & Child', icon: '👩', color: '#ec4899' },
  { id: 'social', label: 'Social Welfare', icon: '🤝', color: '#06b6d4' },
  { id: 'financial', label: 'Financial Inclusion', icon: '💰', color: '#f97316' },
  { id: 'rural', label: 'Rural Development', icon: '🏘️', color: '#84cc16' },
  { id: 'energy', label: 'Energy', icon: '⚡', color: '#eab308' },
  { id: 'digital', label: 'Digital India', icon: '💻', color: '#6366f1' },
  { id: 'minority', label: 'Minority Welfare', icon: '🌙', color: '#14b8a6' },
];

export const mockSchemes: Scheme[] = [
  {
    id: '1',
    name: 'PM Kisan Samman Nidhi',
    nameHi: 'पीएम किसान सम्मान निधि',
    description: 'Income support of ₹6,000 per year to all farmer families across the country in three equal installments of ₹2,000 each, every four months. The scheme aims to supplement the financial needs of small and marginal farmers.',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    schemeType: 'central',
    targetState: null,
    benefits: '₹6,000 per year in 3 installments of ₹2,000 directly to bank account',
    minAge: 18,
    maxAge: null,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: true,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://pmkisan.gov.in',
    deadline: '2026-12-31',
    documentsRequired: ['Aadhaar Card', 'Bank Account Details', 'Land Records'],
    isActive: true,
  },
  {
    id: '2',
    name: 'Ayushman Bharat - PMJAY',
    nameHi: 'आयुष्मान भारत - पीएमजेएवाई',
    description: 'World\'s largest health insurance scheme providing free health coverage of ₹5 lakh per family per year for secondary and tertiary care hospitalization. Covers over 1,900 medical procedures including pre and post hospitalization expenses.',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    schemeType: 'central',
    targetState: null,
    benefits: '₹5 lakh free health insurance coverage per family per year',
    minAge: null,
    maxAge: null,
    minIncome: null,
    maxIncome: 300000,
    targetGender: 'all',
    targetCategories: ['obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: true,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://pmjay.gov.in',
    deadline: null,
    documentsRequired: ['Aadhaar Card', 'Ration Card', 'Income Certificate', 'BPL Certificate'],
    isActive: true,
  },
  {
    id: '3',
    name: 'PM Awas Yojana (Urban)',
    nameHi: 'पीएम आवास योजना (शहरी)',
    description: 'Affordable housing for urban poor with a target to build 2 crore affordable houses. The scheme provides central assistance through interest subsidy on home loans up to ₹2.67 lakh for EWS and LIG categories.',
    ministry: 'Ministry of Housing & Urban Affairs',
    category: 'housing',
    schemeType: 'central',
    targetState: null,
    benefits: 'Interest subsidy up to ₹2.67 lakh on home loans for affordable housing',
    minAge: 21,
    maxAge: 65,
    minIncome: null,
    maxIncome: 600000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://pmaymis.gov.in',
    deadline: '2026-03-31',
    documentsRequired: ['Aadhaar Card', 'Income Certificate', 'Address Proof', 'Bank Account', 'No Property Certificate'],
    isActive: true,
  },
  {
    id: '4',
    name: 'Sukanya Samriddhi Yojana',
    nameHi: 'सुकन्या समृद्धि योजना',
    description: 'A small savings scheme for the girl child offering an attractive interest rate of 8.2% per annum. Parents can open an account for girls below 10 years of age, with minimum deposit of ₹250 per year.',
    ministry: 'Ministry of Finance',
    category: 'women',
    schemeType: 'central',
    targetState: null,
    benefits: '8.2% interest rate per annum, tax benefits under 80C, maturity at age 21',
    minAge: 0,
    maxAge: 10,
    minIncome: null,
    maxIncome: null,
    targetGender: 'female',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://www.india.gov.in/sukanya-samriddhi-yojna',
    deadline: null,
    documentsRequired: ['Birth Certificate of Girl Child', 'Aadhaar Card of Parent', 'Address Proof', 'Photograph'],
    isActive: true,
  },
  {
    id: '5',
    name: 'PM Mudra Yojana',
    nameHi: 'पीएम मुद्रा योजना',
    description: 'Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises. Three categories: Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 lakh), and Tarun (₹5 lakh to ₹10 lakh).',
    ministry: 'Ministry of Finance',
    category: 'financial',
    schemeType: 'central',
    targetState: null,
    benefits: 'Collateral-free loans up to ₹10 lakh for small business entrepreneurs',
    minAge: 18,
    maxAge: 65,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://www.mudra.org.in',
    deadline: null,
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Business Plan', 'Address Proof', 'Passport Photo'],
    isActive: true,
  },
  {
    id: '6',
    name: 'National Scholarship Portal',
    nameHi: 'राष्ट्रीय छात्रवृत्ति पोर्टल',
    description: 'One-stop platform for various scholarships offered by Central Government, State Government and UGC/AICTE for students from class 1 to PhD level. Covers pre-matric, post-matric and merit-cum-means scholarships.',
    ministry: 'Ministry of Education',
    category: 'education',
    schemeType: 'central',
    targetState: null,
    benefits: 'Scholarships ranging from ₹1,000 to ₹75,000 per annum based on course level',
    minAge: 5,
    maxAge: 35,
    minIncome: null,
    maxIncome: 800000,
    targetGender: 'all',
    targetCategories: ['obc', 'sc', 'st', 'ews'],
    targetEducation: ['primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://scholarships.gov.in',
    deadline: '2026-10-31',
    documentsRequired: ['Aadhaar Card', 'Marksheets', 'Income Certificate', 'Caste Certificate', 'Bank Account', 'Institute Verification'],
    isActive: true,
  },
  {
    id: '7',
    name: 'PM Vishwakarma Yojana',
    nameHi: 'पीएम विश्वकर्मा योजना',
    description: 'End-to-end support to traditional artisans and craftspeople through recognition, skill upgradation, toolkit incentive, credit support up to ₹3 lakh, and market linkage for 18 identified trades.',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    category: 'employment',
    schemeType: 'central',
    targetState: null,
    benefits: 'Free skill training, toolkit incentive of ₹15,000, loans up to ₹3 lakh at 5% interest',
    minAge: 18,
    maxAge: null,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://pmvishwakarma.gov.in',
    deadline: '2027-03-31',
    documentsRequired: ['Aadhaar Card', 'Skill Certificate/Self Declaration', 'Bank Account', 'Caste Certificate'],
    isActive: true,
  },
  {
    id: '8',
    name: 'PM Surya Ghar: Free Electricity',
    nameHi: 'पीएम सूर्य घर: मुफ्त बिजली',
    description: 'Install rooftop solar panels and get up to 300 units of free electricity per month. Central financial assistance of up to ₹78,000 for residential rooftop solar installations.',
    ministry: 'Ministry of New and Renewable Energy',
    category: 'energy',
    schemeType: 'central',
    targetState: null,
    benefits: 'Subsidy up to ₹78,000 for solar panel installation, 300 units free electricity/month',
    minAge: 18,
    maxAge: null,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://pmsuryaghar.gov.in',
    deadline: '2027-03-31',
    documentsRequired: ['Aadhaar Card', 'Electricity Bill', 'Roof Ownership Proof', 'Bank Account', 'Photograph'],
    isActive: true,
  },
  {
    id: '9',
    name: 'MGNREGA',
    nameHi: 'मनरेगा',
    description: 'Guarantees 100 days of wage employment per year to every rural household whose adult members volunteer to do unskilled manual work at minimum wage rate of ₹267-332 per day.',
    ministry: 'Ministry of Rural Development',
    category: 'rural',
    schemeType: 'central',
    targetState: null,
    benefits: '100 days guaranteed employment per year at ₹267-332/day in rural areas',
    minAge: 18,
    maxAge: null,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://nrega.nic.in',
    deadline: null,
    documentsRequired: ['Aadhaar Card', 'Job Card', 'Bank Account', 'Photograph'],
    isActive: true,
  },
  {
    id: '10',
    name: 'Ujjwala Yojana 2.0',
    nameHi: 'उज्ज्वला योजना 2.0',
    description: 'Provides free LPG connections to women from BPL households. Also provides first LPG refill and hotplate free of cost to make clean cooking fuel accessible to all.',
    ministry: 'Ministry of Petroleum & Natural Gas',
    category: 'women',
    schemeType: 'central',
    targetState: null,
    benefits: 'Free LPG connection, first refill, and hotplate for BPL women',
    minAge: 18,
    maxAge: null,
    minIncome: null,
    maxIncome: 200000,
    targetGender: 'female',
    targetCategories: ['obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: true,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://www.pmujjwalayojana.com',
    deadline: null,
    documentsRequired: ['Aadhaar Card', 'BPL Certificate', 'Ration Card', 'Bank Account', 'Photograph'],
    isActive: true,
  },
  {
    id: '11',
    name: 'Digital India - Free WiFi',
    nameHi: 'डिजिटल इंडिया - मुफ्त वाईफाई',
    description: 'Providing broadband connectivity to 2.5 lakh gram panchayats through BharatNet. Free public WiFi hotspots in rural and semi-urban areas for digital empowerment.',
    ministry: 'Ministry of Electronics & IT',
    category: 'digital',
    schemeType: 'central',
    targetState: null,
    benefits: 'Free public WiFi access, digital literacy training, online service access',
    minAge: null,
    maxAge: null,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['none', 'primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://digitalindia.gov.in',
    deadline: null,
    documentsRequired: ['Aadhaar Card'],
    isActive: true,
  },
  {
    id: '12',
    name: 'PM Internship Scheme',
    nameHi: 'पीएम इंटर्नशिप योजना',
    description: 'Provides 12-month internship opportunities to youth aged 21-24 in top 500 companies. Monthly assistance of ₹5,000 and one-time grant of ₹6,000 for incidental expenses.',
    ministry: 'Ministry of Corporate Affairs',
    category: 'employment',
    schemeType: 'central',
    targetState: null,
    benefits: '₹5,000/month stipend + ₹6,000 one-time grant, industry exposure for 12 months',
    minAge: 21,
    maxAge: 24,
    minIncome: null,
    maxIncome: 800000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: false,
    requiresDisability: false,
    applicationUrl: 'https://pminternship.mca.gov.in',
    deadline: '2026-09-30',
    documentsRequired: ['Aadhaar Card', 'Educational Certificates', 'Resume', 'Bank Account', 'Photograph'],
    isActive: true,
  },

  // ─────────────────────────────────────────────────────────────────────
  // STUDENT & SCHOLARSHIP SCHEMES — GOVERNMENT
  // ─────────────────────────────────────────────────────────────────────
  {
    id: '13',
    name: 'PM-USP Central Sector Scholarship',
    nameHi: 'पीएम उच्चतर शिक्षा प्रोत्साहन योजना',
    description: 'Pradhan Mantri Uchchatar Shiksha Protsahan provides financial assistance to meritorious students from low-income families pursuing graduate/postgraduate courses. Top 0.1% students from each Class 12 board stream are eligible via National Scholarship Portal.',
    ministry: 'Ministry of Education',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: '₹10,000/year for undergraduate and ₹20,000/year for postgraduate students',
    minAge: 17,
    maxAge: 25,
    minIncome: null,
    maxIncome: 800000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://scholarships.gov.in',
    deadline: '2026-10-31',
    documentsRequired: ['Aadhaar Card', '12th Marksheet (top 1% in board)', 'Income Certificate (max ₹8L)', 'Admission Letter', 'Bank Account'],
    isActive: true,
  },
  {
    id: '14',
    name: 'Post-Matric Scholarship for SC Students',
    nameHi: 'पोस्ट-मैट्रिक छात्रवृत्ति (एससी छात्र)',
    description: 'Post-Matric Scholarship for Scheduled Caste students covering maintenance allowance, tuition fees, study tour charges and thesis/dissertation charges. Available for classes 11-12, diploma, undergraduate, postgraduate and research degree courses.',
    ministry: 'Ministry of Social Justice & Empowerment',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: 'Full tuition fee reimbursement + maintenance allowance ₹1,200 to ₹3,800/month',
    minAge: null,
    maxAge: 35,
    minIncome: null,
    maxIncome: 250000,
    targetGender: 'all',
    targetCategories: ['sc'],
    targetEducation: ['secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://mahadbt.maharashtra.gov.in',
    deadline: '2026-11-30',
    documentsRequired: ['Aadhaar Card', 'SC Certificate', 'Income Certificate', 'Previous Marksheet', 'Bank Account', 'Admission Receipt'],
    isActive: true,
  },
  {
    id: '15',
    name: 'Post-Matric Scholarship for ST Students',
    nameHi: 'पोस्ट-मैट्रिक छात्रवृत्ति (एसटी छात्र)',
    description: 'Scholarship for Scheduled Tribe students at post-matriculation level (class 11 through research). Covers academic expenses and maintenance allowance for hostellers and day scholars enrolled in any recognized government or private college.',
    ministry: 'Ministry of Tribal Affairs',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: 'Full course fee + maintenance allowance up to ₹3,000/month for hostellers',
    minAge: null,
    maxAge: null,
    minIncome: null,
    maxIncome: 250000,
    targetGender: 'all',
    targetCategories: ['st'],
    targetEducation: ['secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://mahadbt.maharashtra.gov.in',
    deadline: '2026-11-30',
    documentsRequired: ['Aadhaar Card', 'Tribe Certificate', 'Income Certificate', 'Admission Letter', 'Bank Account'],
    isActive: true,
  },
  {
    id: '16',
    name: 'OBC Pre & Post-Matric Scholarship',
    nameHi: 'ओबीसी प्री एवं पोस्ट-मैट्रिक छात्रवृत्ति',
    description: 'Scholarship for Other Backward Classes students from class 9 through postgraduate. Monthly stipend and course fee reimbursement to encourage OBC students to continue higher education without financial burden.',
    ministry: 'Ministry of Social Justice & Empowerment',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: 'Pre-matric: ₹1,000–₹1,500/month; Post-matric: ₹1,200–₹3,000/month + fee reimbursement',
    minAge: null,
    maxAge: 30,
    minIncome: null,
    maxIncome: 300000,
    targetGender: 'all',
    targetCategories: ['obc'],
    targetEducation: ['secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://mahadbt.maharashtra.gov.in',
    deadline: '2026-10-31',
    documentsRequired: ['Aadhaar Card', 'OBC Certificate', 'Income Certificate', 'Marksheet', 'Bank Account'],
    isActive: true,
  },
  {
    id: '17',
    name: 'PM Scholarship for Armed Forces Wards',
    nameHi: 'सशस्त्र बल वार्ड हेतु पीएम छात्रवृत्ति',
    description: 'PM Scholarship Scheme for wards and widows of ex-servicemen, para-military and Assam Rifles. Covers technical and first professional degree courses. Priority to wards of personnel killed or disabled in action.',
    ministry: 'Ministry of Defence / Kendriya Sainik Board',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: '₹2,500/month for male scholars and ₹3,000/month for female scholars (up to 5 years)',
    minAge: 18,
    maxAge: 25,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://ksb.gov.in/pm-scholarship.htm',
    deadline: '2026-09-30',
    documentsRequired: ['Aadhaar Card', 'Ex-Serviceman PPO / Discharge Book', 'Marksheet', 'Bonafide Certificate', 'Bank Account'],
    isActive: true,
  },
  {
    id: '18',
    name: 'Top Class Education Scheme for SC (IIT/NIT/AIIMS)',
    nameHi: 'टॉप क्लास एजुकेशन स्कीम एससी',
    description: 'Full scholarship for SC students admitted to top notified institutions (IITs, IIMs, NITs, AIIMS, National Law Universities). Provides complete financial support including tuition fee, living allowance, books, and computer purchase grant.',
    ministry: 'Ministry of Social Justice & Empowerment',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: 'Full tuition fee + ₹1.5L/year living allowance + ₹45,000 books + ₹45,000 computer allowance',
    minAge: null,
    maxAge: 30,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['sc'],
    targetEducation: ['graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://scholarships.gov.in',
    deadline: '2026-10-31',
    documentsRequired: ['Aadhaar Card', 'SC Certificate', 'Notified Institution Admission Letter', 'Marksheet', 'Bank Account'],
    isActive: true,
  },
  {
    id: '19',
    name: 'Begum Hazrat Mahal Scholarship (Minority Girls)',
    nameHi: 'बेगम हजरत महल राष्ट्रीय छात्रवृत्ति',
    description: 'Scholarship for meritorious girls from minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) in classes 9–12. Supports girl education in minority families who scored at least 50% marks in previous examination.',
    ministry: 'Maulana Azad Education Foundation (MAEF)',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: '₹5,000 for class 9-10 and ₹6,000 for class 11-12 per year',
    minAge: 13,
    maxAge: 20,
    minIncome: null,
    maxIncome: 200000,
    targetGender: 'female',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['secondary'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://maef.nic.in',
    deadline: '2026-09-30',
    documentsRequired: ['Aadhaar Card', 'Minority Community Certificate', 'Income Certificate', 'Marksheet (min 50%)', 'Bank Account'],
    isActive: true,
  },
  {
    id: '20',
    name: 'Ishan Uday Scholarship for North-East Students',
    nameHi: 'ईशान उदय छात्रवृत्ति (पूर्वोत्तर)',
    description: 'Special UGC scholarship for students from all 8 North-Eastern states who secured admission in colleges outside their home state. Monthly scholarship to support living and education costs away from home.',
    ministry: 'University Grants Commission (UGC)',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: '₹5,400/month for general courses and ₹7,800/month for technical/medical/professional courses',
    minAge: 17,
    maxAge: 24,
    minIncome: null,
    maxIncome: 450000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://www.ugc.gov.in/page/Ishan-Uday.aspx',
    deadline: '2026-09-30',
    documentsRequired: ['Aadhaar Card', 'Domicile Certificate (NE State)', 'Income Certificate', 'Admission Letter', 'Marksheet', 'Bank Account'],
    isActive: true,
  },
  {
    id: '21',
    name: 'INSPIRE Scholarship for Science (DST)',
    nameHi: 'इंस्पायर छात्रवृत्ति DST (विज्ञान)',
    description: 'Innovation in Science Pursuit for Inspired Research (INSPIRE-SHE) attracts talented students to basic and natural science courses (BSc, BS, Int. MSc/MS). One of India\'s most generous science scholarships covering 5 years.',
    ministry: 'Department of Science & Technology (DST)',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: '₹80,000/year = ₹60,000 scholarship + ₹20,000 mentorship grant for 5 years',
    minAge: 17,
    maxAge: 22,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://online-inspire.gov.in',
    deadline: '2026-09-15',
    documentsRequired: ['Aadhaar Card', '12th Marksheet (top 1% in board exam)', 'BSc/Int. MSc Admission Letter', 'Bank Account'],
    isActive: true,
  },
  {
    id: '22',
    name: 'Disability Post-Matric Scholarship (Divyangjan)',
    nameHi: 'दिव्यांग पोस्ट-मैट्रिक छात्रवृत्ति',
    description: 'Comprehensive scholarship for students with 40%+ certified disability. Provides maintenance allowance, disability allowance, reader allowance for visually impaired, transport, and full course fee reimbursement for all recognized courses.',
    ministry: 'Ministry of Social Justice & Empowerment (DEPwD)',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: '₹1,000–₹3,000/month maintenance + ₹2,000/month disability allowance + full fee reimbursement',
    minAge: null,
    maxAge: 35,
    minIncome: null,
    maxIncome: 250000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: true,
    applicationUrl: 'https://scholarships.gov.in',
    deadline: '2026-10-31',
    documentsRequired: ['Aadhaar Card', 'Disability Certificate (min 40%)', 'Income Certificate', 'Marksheet', 'Bank Account'],
    isActive: true,
  },

  // ─────────────────────────────────────────────────────────────────────
  // STUDENT & SCHOLARSHIP SCHEMES — PRIVATE INDUSTRY / CORPORATE CSR
  // ─────────────────────────────────────────────────────────────────────
  {
    id: '23',
    name: 'Reliance Foundation UG Scholarship',
    nameHi: 'रिलायंस फाउंडेशन अंडरग्रेजुएट छात्रवृत्ति',
    description: 'Reliance Foundation scholarships for 5,000 meritorious first-year undergraduate students from any stream across India. Mandatory online aptitude test. Preferential consideration for family income below ₹2.5 Lakh.',
    ministry: 'Reliance Foundation (Private CSR)',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'private_industry',
    sourceOrg: 'Reliance Foundation',
    targetState: null,
    benefits: 'UG: Up to ₹2,00,000 over degree (annually). PG (select STEM): up to ₹6,00,000.',
    minAge: 17,
    maxAge: 22,
    minIncome: null,
    maxIncome: 1500000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://rf.scholarshiponline.in',
    deadline: '2026-09-30',
    documentsRequired: ['Aadhaar Card', '12th Marksheet (min 60%)', 'Income Certificate', 'Admission Letter', 'Bank Account'],
    isActive: true,
  },
  {
    id: '24',
    name: 'Tata Capital Pankh Scholarship',
    nameHi: 'टाटा कैपिटल पंख छात्रवृत्ति',
    description: 'Tata Capital Pankh Scholarship gives financial wings to students from economically weaker sections in classes 11-12, undergraduate, diploma, and ITI courses. One of India\'s most accessible corporate scholarships with wide eligibility.',
    ministry: 'Tata Capital Ltd. (Private CSR)',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'private_industry',
    sourceOrg: 'Tata Capital',
    targetState: null,
    benefits: 'Up to ₹1,00,000 covering tuition fees, books, and living expenses per year',
    minAge: 15,
    maxAge: 30,
    minIncome: null,
    maxIncome: 250000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['secondary', 'graduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://www.buddy4study.com/tata-capital-pankh-scholarship',
    deadline: '2026-08-31',
    documentsRequired: ['Aadhaar Card', 'Income Certificate (max ₹2.5L)', 'Marksheet (min 60%)', 'Admission Letter', 'Bank Account'],
    isActive: true,
  },
  {
    id: '25',
    name: 'Aditya Birla Scholarship (IIT/IIM/NLU Students)',
    nameHi: 'आदित्य बिड़ला स्कॉलरशिप (IIT/IIM/NLU)',
    description: 'Prestigious Aditya Birla Scholarship for top-ranked students at IITs, IIMs, BITS Pilani, and National Law Schools. Top 20 students from each institute are invited through Dean nomination. Covers significant portion of fees for full degree.',
    ministry: 'Aditya Birla Group (Private CSR)',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'private_industry',
    sourceOrg: 'Aditya Birla Group',
    targetState: null,
    benefits: 'Engineering: ₹1.5L/year | Management (IIM): ₹3L/year | Law (NLU): ₹1.8L/year',
    minAge: 17,
    maxAge: 30,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://www.adityabirlascholars.net',
    deadline: null,
    documentsRequired: ['Institute Dean Nomination', 'JEE/CAT/CLAT Rank Card', 'Aadhaar Card', 'Admission Proof'],
    isActive: true,
  },
  {
    id: '26',
    name: 'Infosys Foundation STEM Stars (Women in STEM)',
    nameHi: 'इंफोसिस फाउंडेशन स्टेम स्टार्स',
    description: 'Infosys Foundation STEM Stars Scholarship bridges the gender gap in technology by supporting female students pursuing undergraduate STEM degrees at NIRF-accredited institutions. Covers all major educational expenses.',
    ministry: 'Infosys Foundation (Private CSR)',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'private_industry',
    sourceOrg: 'Infosys Foundation',
    targetState: null,
    benefits: 'Up to ₹1,00,000/year for tuition + living expenses + study materials for full degree',
    minAge: 17,
    maxAge: 22,
    minIncome: null,
    maxIncome: 800000,
    targetGender: 'female',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://www.infosys.com/infosys-foundation',
    deadline: '2026-09-30',
    documentsRequired: ['Aadhaar Card', 'Income Certificate (max ₹8L)', '12th Marksheet', 'STEM Admission Letter at NIRF Institution', 'Bank Account'],
    isActive: true,
  },
  {
    id: '27',
    name: 'Sitaram Jindal Foundation Scholarship',
    nameHi: 'सीताराम जिंदल फाउंडेशन छात्रवृत्ति',
    description: 'Sitaram Jindal Foundation scholarship for meritorious and financially needy students in government colleges — from class 11 through postgraduate. One of India\'s most accessible and broad-eligibility corporate scholarships.',
    ministry: 'Sitaram Jindal Foundation (Private CSR)',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'private_industry',
    sourceOrg: 'Sitaram Jindal Foundation',
    targetState: null,
    benefits: '₹1,000–₹3,000/month depending on course level, paid throughout the academic year',
    minAge: 15,
    maxAge: 30,
    minIncome: null,
    maxIncome: 250000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://sitaramjindalfoundation.org',
    deadline: '2026-10-31',
    documentsRequired: ['Aadhaar Card', 'Income Certificate', 'Marksheet', 'Government College Proof', 'Bank Account'],
    isActive: true,
  },
  {
    id: '28',
    name: 'Google Generation Scholarship (Women in Tech)',
    nameHi: 'गूगल जेनरेशन स्कॉलरशिप',
    description: 'Google Generation Scholarship promotes diversity in technology by supporting women studying computer science or related technical fields. Recipients also get Google mentorship and networking opportunities with Google engineers across India.',
    ministry: 'Google India (Private CSR)',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'private_industry',
    sourceOrg: 'Google India',
    targetState: null,
    benefits: '₹75,000 one-time scholarship + Google mentorship program + Google engineer networking',
    minAge: 17,
    maxAge: 25,
    minIncome: null,
    maxIncome: null,
    targetGender: 'female',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://buildyourfuture.withgoogle.com/scholarships',
    deadline: '2026-12-31',
    documentsRequired: ['Resume/CV', 'Academic Transcripts', 'Leadership & Academics Essay', 'CS/Tech Course Enrollment Proof'],
    isActive: true,
  },
  {
    id: '29',
    name: 'Maruti Suzuki ITI Scholarship',
    nameHi: 'मारुति सुजुकी आईटीआई छात्रवृत्ति',
    description: 'Maruti Suzuki scholarship for outstanding ITI students in automobile and engineering trades. Financial support plus potential placement opportunities in Maruti Suzuki manufacturing plants and India\'s largest dealer network.',
    ministry: 'Maruti Suzuki India Ltd. (Private CSR)',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'private_industry',
    sourceOrg: 'Maruti Suzuki India',
    targetState: null,
    benefits: '₹10,000–₹15,000/year scholarship + placement opportunity in Maruti Suzuki dealer network',
    minAge: 16,
    maxAge: 25,
    minIncome: null,
    maxIncome: 300000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['secondary'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://www.marutisuzuki.com/corporate/csr',
    deadline: '2026-08-31',
    documentsRequired: ['Aadhaar Card', 'ITI Admission Proof', 'Income Certificate', 'Marksheet', 'Bank Account'],
    isActive: true,
  },
  {
    id: '30',
    name: 'Swami Vivekananda Merit-cum-Means Scholarship',
    nameHi: 'स्वामी विवेकानंद मेरिट-कम-मीन्स छात्रवृत्ति',
    description: 'UGC Merit-cum-Means Scholarship for graduate and postgraduate students in professional/technical courses. Balances merit and financial need. Applied via National Scholarship Portal for university-level students across India.',
    ministry: 'University Grants Commission (UGC)',
    category: 'scholarship',
    schemeType: 'central',
    schemeSource: 'government',
    targetState: null,
    benefits: '₹1,000–₹2,000/month throughout the degree for technical and professional courses',
    minAge: 17,
    maxAge: 30,
    minIncome: null,
    maxIncome: 250000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://scholarships.gov.in',
    deadline: '2026-11-30',
    documentsRequired: ['Aadhaar Card', 'Income Certificate', '12th Marksheet', 'University Admission Proof', 'Bank Account'],
    isActive: true,
  },
  {
    id: '31',
    name: 'Buddy4Study — India Scholarship Search Portal',
    nameHi: 'बडी4स्टडी — छात्रवृत्ति खोज पोर्टल',
    description: "India's largest scholarship aggregator giving access to 3,000+ scholarships from government, NGOs, and private companies. Students search, apply, and track multiple scholarship applications simultaneously through one platform.",
    ministry: 'Buddy4Study Platform',
    category: 'scholarship',
    schemeType: 'private',
    schemeSource: 'ngo',
    sourceOrg: 'Buddy4Study',
    targetState: null,
    benefits: 'Access to 3,000+ scholarships ranging from ₹1,000 to ₹10 Lakh based on individual schemes',
    minAge: null,
    maxAge: null,
    minIncome: null,
    maxIncome: null,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['primary', 'secondary', 'graduate', 'postgraduate'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://www.buddy4study.com',
    deadline: null,
    documentsRequired: ['Aadhaar Card', 'Marksheet', 'Bank Account'],
    isActive: true,
  },
  {
    id: '32',
    name: 'MahaDBT Rajarshi Chhatrapati Shahu Maharaj (EBC)',
    nameHi: 'महाडीबीटी राजर्षी छत्रपती शाहू महाराज शिक्षण शुल्क (ईबीसी)',
    description: 'Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (EBC) provides 50% tuition and exam fee reimbursement for students admitted to professional courses like Engineering, Medical, and Pharmacy through CAP rounds. Open to all categories.',
    ministry: 'Directorate of Technical Education (DTE), Maharashtra',
    category: 'scholarship',
    schemeType: 'state',
    schemeSource: 'government',
    targetState: 'Maharashtra',
    benefits: '50% reimbursement of Tuition Fees and Exam Fees for professional degree courses',
    minAge: 17,
    maxAge: 30,
    minIncome: null,
    maxIncome: 800000,
    targetGender: 'all',
    targetCategories: ['general', 'obc', 'sc', 'st', 'ews'],
    targetEducation: ['secondary'],
    requiresBpl: false,
    requiresFarmer: false,
    requiresStudent: true,
    requiresDisability: false,
    applicationUrl: 'https://mahadbt.maharashtra.gov.in/',
    deadline: '2026-12-31',
    documentsRequired: ['Aadhaar Card', '12th Marksheet', 'Income Certificate (max ₹8L)', 'CAP Allotment Letter', 'Fee Receipt', 'Bank Account'],
    isActive: true,
  }
];

export const mockUserProfile: UserProfile = {
  id: '1',
  phone: '+91 98765 43210',
  name: 'Rajesh Kumar',
  email: 'rajesh.kumar@email.com',
  dateOfBirth: '1995-03-15',
  gender: 'male',
  category: 'obc',
  state: 'Uttar Pradesh',
  district: 'Lucknow',
  annualIncome: 250000,
  occupation: 'Farmer',
  educationLevel: 'secondary',
  isDisabled: false,
  isMinority: false,
  isBpl: false,
  isFarmer: true,
  isStudent: false,
  preferredLanguage: 'en',
};

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  type: 'deadline' | 'new_scheme' | 'eligibility' | 'system';
  isRead: boolean;
  timestamp: Date;
  schemeId?: string;
}

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Deadline Approaching',
    message: 'PM Awas Yojana application deadline is on March 31, 2026. Apply now!',
    type: 'deadline',
    isRead: false,
    timestamp: new Date('2026-06-14'),
    schemeId: '3',
  },
  {
    id: '2',
    title: 'New Scheme Available',
    message: 'PM Internship Scheme has been launched. Check your eligibility!',
    type: 'new_scheme',
    isRead: false,
    timestamp: new Date('2026-06-13'),
    schemeId: '12',
  },
  {
    id: '3',
    title: 'High Eligibility Match',
    message: 'You are 95% eligible for PM Kisan Samman Nidhi. Complete your application today.',
    type: 'eligibility',
    isRead: true,
    timestamp: new Date('2026-06-12'),
    schemeId: '1',
  },
  {
    id: '4',
    title: 'Profile Incomplete',
    message: 'Complete your profile to get better scheme recommendations.',
    type: 'system',
    isRead: true,
    timestamp: new Date('2026-06-10'),
  },
];

// Analytics mock data
export const analyticsData = {
  totalUsers: 15420,
  totalSchemes: 156,
  totalApplications: 42580,
  activeUsers: 8930,
  monthlyUsers: [
    { month: 'Jan', users: 1200 },
    { month: 'Feb', users: 1800 },
    { month: 'Mar', users: 2400 },
    { month: 'Apr', users: 3100 },
    { month: 'May', users: 4200 },
    { month: 'Jun', users: 5100 },
  ],
  schemesByCategory: [
    { category: 'Agriculture', count: 28, color: '#22c55e' },
    { category: 'Education', count: 24, color: '#3b82f6' },
    { category: 'Health', count: 20, color: '#ef4444' },
    { category: 'Housing', count: 15, color: '#f59e0b' },
    { category: 'Employment', count: 18, color: '#8b5cf6' },
    { category: 'Women', count: 12, color: '#ec4899' },
    { category: 'Financial', count: 16, color: '#f97316' },
    { category: 'Others', count: 23, color: '#64748b' },
  ],
  topStates: [
    { state: 'Uttar Pradesh', users: 3200 },
    { state: 'Maharashtra', users: 2800 },
    { state: 'Bihar', users: 2100 },
    { state: 'Rajasthan', users: 1900 },
    { state: 'Madhya Pradesh', users: 1600 },
  ],
  eligibilityDistribution: [
    { range: '90-100%', count: 1200 },
    { range: '70-89%', count: 3400 },
    { range: '50-69%', count: 4800 },
    { range: '30-49%', count: 3200 },
    { range: '0-29%', count: 2820 },
  ],
};

// Helper function to calculate eligibility score
export function calculateEligibilityScore(scheme: Scheme, user: UserProfile): number {
  // HARD CONSTRAINTS (Immediate Rejection)
  if (scheme.requiresDisability && !user.isDisabled) return 0;
  if (scheme.requiresBpl && !user.isBpl) return 0;
  if (scheme.requiresFarmer && !user.isFarmer) return 0;
  if (scheme.requiresStudent && !user.isStudent) return 0;
  if (scheme.targetGender !== 'all' && scheme.targetGender !== user.gender) return 0;
  if (scheme.targetCategories.length > 0 && !scheme.targetCategories.includes(user.category)) return 0;
  if (scheme.targetState && scheme.targetState !== user.state) return 0;

  // Student Persona strict filtering (User request: Students should only see scholarships/education)
  if (user.isStudent && scheme.category !== 'scholarship' && scheme.category !== 'education' && !scheme.requiresStudent) {
    return 0;
  }

  // Age hard rejection
  const age = new Date().getFullYear() - new Date(user.dateOfBirth).getFullYear();
  if (scheme.minAge !== null && age < scheme.minAge) return 0;
  if (scheme.maxAge !== null && age > scheme.maxAge) return 0;

  // Income hard rejection
  if (scheme.maxIncome !== null && user.annualIncome > scheme.maxIncome) return 0;
  if (scheme.minIncome !== null && user.annualIncome < scheme.minIncome) return 0;

  // Education hard rejection
  if (scheme.targetEducation.length > 0 && !scheme.targetEducation.includes(user.educationLevel)) return 0;

  // If passed all constraints, base score is very high (highly relevant)
  let score = 90;

  // Bonus points for highly targeted schemes
  if (scheme.targetCategories.length > 0) score += 5; 
  if (scheme.targetGender !== 'all') score += 5;

  return Math.min(100, score);
}
